---
title: "P8105_hw1_sim2128"
author: "Sarah Munro"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(tidyverse)

#Problem 1

```{r}
set.seed(10)
hw1_df = tibble(
  sharks = rnorm(8),
  positive = sharks > 0, 
  species = c("White", "Tiger", "Nurse", "Bull", "Whale", "Lemon", "Hammerhead",   "Mako"),
  aggression = factor(c("High", "High", "Low", "High", "Low", "High", "Medium", "Medium"))
)

mean(pull(hw1_df, sharks))
#The mean was taken properly
mean(pull(hw1_df, positive))
#The mean was taken properly
mean(pull(hw1_df, species))
#The mean was unable to be taken
mean(pull(hw1_df, aggression))
#The mean was unable to be taken
```

```{r eval = FALSE}
#Convert the logical vector to a numeric vector
as.numeric(pull(hw1_df, positive))
#Convert the character vector to a numeric vector
as.numeric(pull(hw1_df, species))
#Convert the factor vector to a numeric vector
as.numeric(pull(hw1_df, aggression))

#You can convert the logical and factor vectors to numeric, but you are unable to covert the character vector to numeric. This would explain why the mean of the character variable cannot be taken, the characters do not correspond to any numeric values. 
```

```{r}
#Convert the logical vector to a numeric vector, then multiply the random sample by the result
as.numeric(pull(hw1_df, positive))*(pull(hw1_df, sharks))
#Convert the logical vector to a factor vector, then multiply the random sample by the result
as.factor(pull(hw1_df, positive))*(pull(hw1_df, sharks))
#Convert the logical vector to a factor factor, then convert the result to numeric, then multiply the random sample by the result
as.numeric(as.factor(pull(hw1_df, positive)))*(pull(hw1_df, sharks))

#The result was not meaningful for the factors, they were assigned values of NA

```

#Problem 2 

```{r}
set.seed(500)
part2_df = tibble(
  x = rnorm(500),
  y = rnorm(500),
  logicv = x + y > 1,
  numberv = as.numeric(logicv),
  factorv = as.factor(numberv)
)

```
The dataset `part2_df1` has `r nrow(part2_df)` rows and `r ncol(part2_df)` columns. The mean of x is `r mean(pull(part2_df, x))`, the median is `r median(pull(part2_df, x))`, and the standard deviation is `r sd(pull(part2_df, x))`. The proportion of `logicv` for which x + y > 1 is `r mean(pull(part2_df, logicv))`

```{r}
#Scatter plot with colors corresponding to the logical vector
ggplot(part2_df, aes(x = x, y = y, color=logicv)) + geom_point()
ggsave("scatter_plot1.pdf")
#Scatter plot with colors corresponding to the numeric vector
ggplot(part2_df, aes(x = x, y = y, color=numberv)) + geom_point()
#Scatter plot with colors corresponding to the factor vector
ggplot(part2_df, aes(x = x, y = y, color=factorv)) + geom_point()

#The distribution appeared the same for all three plots. The colors appeared the same only for the plots corresponding to the logical and factor vector. For the plot with colors corresponding to the numeric vector, there was a scale of color rather than 2 single options of red or blue. 

```

